export const uiActionTypes = {
  OPEN_DRAWER: 'OPEN_DRAWER: ',
  CLOSE_DRAWER: 'CLOSE_DRAWER',
  TOGGLE_DRAWER: 'TOGGLE_DRAWER',
  SET_TITLE: 'SET_TITLE',
  TOGGLE_MISSION_LOG: 'TOGGLE_MISSION_LOG',
  SET_MISSION_LOG_INDEX: 'SET_MISSION_LOG_INDEX',
  MISSION_LOG_NEXT: 'MISSION_LOG_NEXT',
  MISSION_LOG_PREV: 'MISSION_LOG_PREV',
  SET_MISSION_LOG_OFFSET: 'SET_MISSION_LOG_OFFSET'
};
